apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["echo 'hello'; sleep 3600;"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
