#!/usr/bin/env bash
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'RUNNING SECOND SCRIPT..'
echo 'DONE..'


