kind: PersistentVolume
apiVersion: v1
metadata:
  name: earth-project-earthflower-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  hostPath:
    path: /Volumes/Data 
