apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: plt-6cc-api
spec:
  ports:
  - port: 3333
    protocol: TCP
    targetPort: 80
  selector:
    run: plt-6cc-api
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plt-6cc-api
  name: plt-6cc-api
spec:
  containers:
  - image: nginx:1.17.3-alpine
    name: plt-6cc-api
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
