apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: mycron
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: mycron
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the cluster
            image: busybox
            name: mycron
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
