apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: pi
spec:
  parallelism: 5
  completions: 5 
  template:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 30
      containers:
      - command:
        - perl
        - -Mbignum=bpi
        - -wle
        - print bpi(2000)
        image: perl
        name: pi
        resources: {}
      restartPolicy: Never
status: {}
