apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    accelerator:nvidia-tesla-p100
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
