apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /etc/foo
      name: test
    resources: {}
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox2
    volumeMounts:
    - mountPath: /etc/foo
      name: test
    resources: {}
  volumes:
  - name: test
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
