apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: cmvolume
        mountPath: /etc/foo
  volumes:
    - name: cmvolume
      secret:
        secretName: mysecret2      

